site_name: Сборник песен
plugins: 
  - awesome-pages
  - search  
theme:
  name : 'material'
  palette:
    primary: 'brown'
    accent: 'Deep Orange'
  language: 'ru'
extra:
  search:
    language: 'ru, en'
    tokenizer: '[\s\-\.]+'