site_name: Сборник гимнов
plugins: 
  - awesome-pages
  - search
theme:
  name : 'material'
  palette:
    primary: 'brown'
    accent: 'Deep Orange'
  language: 'ru'
  extra:
  search:
    language: 'en, ru'